org.gradle.jvmargs = -Xmx4G
org.gradle.caching = true

loom.ignoreDependencyLoomVersionValidation=true

archives_base_name = CreateReiViewer
mod_version = 1.0.0-fly.26.2-beta.8
maven_group = dev.chaevsfe.createreiviewer

minecraft_version = 26.2
minecraft_dependency_version = 26.2

fabric_loader_version = 0.19.3
fabric_api_version = 0.155.0+26.2
fabric_api_version_range = >=0.155.0

create_fabric_version = 26.2-rc-2-6.0.9-1
create_fabric_version_range = >=6.0.9-1

rei_version = 26.2.820+fabric
rei_version_breaks = <26.2.820
architectury_version = 21.0.7+fabric
cloth_config_version = 26.2.155+fabric
basic_math_version = 0.6.1
jei_version = 30.24.0.165
